### ISSUE TITLE
why sqlx.Stmt never close?

### ISSUE THREAD

**Issue by gosp** [grisha/gowebapp#1]
```
type pgDb struct {
	dbConn *sqlx.DB

	sqlSelectPeople *sqlx.Stmt
	sqlInsertPerson *sqlx.NamedStmt
	sqlSelectPerson *sql.Stmt
}
```
I see your example code. you never close `sqlx.Stmt`. why?
[discuss reference](https://groups.google.com/forum/#!topic/golang-nuts/ISh22XXze-s)

**Comment by grisha** [comment]
Because if a `sqlx.Stmt` is closed, then you can't use it anymore until you `Prepare()` it again? The reference to the prepared statement lives in `*pgDb`, and you can use it again and again throughout the life of the app. Perhaps when the app exits it would be better to `Close()` it, but I'm pretty sure that it's not necessary - Postgres will see that the connection ended and will free the resources.

**Comment by gosp** [comment]
ok
